### ISSUE TITLE
Data Grid Refactor Roadmap

### ISSUE THREAD

**Issue by nzbin** [ng-matero/extensions#4]
- [ ] row selectable
- [ ] multiple row selectable
- [ ] cell selectable
- [ ] multiple cell selectable
- [ ] column hiding option
- [ ] column moving option
- [ ] column pinning option
- [ ] expandable row
- [ ] filter option

**Comment by TejasCMehta** [comment]
@nzbin  you can refer to this https://ag-grid.com/example.php for further enhancement ideas.

**Comment by TejasCMehta** [comment]
how to achieve this type of custom headertemplate with filter inputs like, dropdown, datepicker etc?
![image](https://user-images.githubusercontent.com/5519037/79944344-e88a0700-8488-11ea-9849-57e1e88ebf8e.png)

**Comment by panakour** [comment]
Also I think header and footer template are the most important in the list

**Comment by Laca81** [comment]
> Also I think header and footer template are the most important in the list

Totally agree

**Comment by nzbin** [comment]
@TejasCMehta @panakour @Laca81 
The header and footer template have been added.

**Comment by YuriGrandinetti** [comment]
Hello, I downloaded the extensions and the ng-matero template, and I already upgraded to the new version of angular 10, still without any problems. I am wanting to use a datagrid project for my project, but I would like to know if you have a plan to implement this type of custom headertemplate with filter inputs like, dropdown, datepicker etc?

**Comment by nzbin** [comment]
@YuriGrandinetti I think you should customize the header template with your own logic.

**Comment by YuriGrandinetti** [comment]
ok, You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you

You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you₢


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


You are doing this implementation because I like its coding, simple to
understand and easy to maintain,
thank you


Em qua., 1 de jul. de 2020 às 10:25, Zongbin <notifications@github.com>
escreveu:

**Comment by nzbin** [comment]
@YuriGrandinetti Thanks for your advice，I will add this feature in future.

**Comment by mlribes** [comment]
[matSortActive], [matSortDirection] and matSortDisableClear support are also important in case of backend sort.

**Comment by nzbin** [comment]
> [matSortActive], [matSortDirection] and matSortDisableClear support are also important in case of backend sort.

Many thanks for your PR, I have released a new version.

**Comment by TejasM9** [comment]
@nzbin  can you add right sidebar on the data grid page ? What I need is I want to open a right side bar with search form on the data grid page. can you guide me any better way to do that. I also want to open add/edit form like that too.

**Comment by vladimirdrayling** [comment]
With virtual scroll the performance of grid will be even better.

[Advanced stackblitz example](https://stackblitz.com/edit/mat-table-virtual-scroll-93hk8d)

**Comment by ChrTall** [comment]
@nzbin I have a requirment for selecting different rows and columns in a datagrid. Will this be possible after the datagrid is refactored? Thank you for your work. Is the current state of the refactored Datagrid in the dev branch?

**Comment by nzbin** [comment]
> @nzbin I have a requirment for selecting different rows and columns in a datagrid. Will this be possible after the datagrid is refactored? Thank you for your work. Is the current state of the refactored Datagrid in the dev branch?

Have you checked the [examples](https://ng-matero.github.io/extensions/components/data-grid/overview)?

**Comment by ChrTall** [comment]
@nzbin Yes I have read them. I think I can achieve my goal by using a Custom header template with a checkbox. I have problems to use fxLayout inside the ng-template for expandable rows. Is this not possible or are there any gotchas ?

**Comment by ismailix** [comment]
I am using the data-grid structure in one of my projects, but it seems a bit plain.
How can I export (pdf - excel) and filter and search within the table? thanks @nzbin

**Comment by ramax495** [comment]
When using material table we can init data with `dataSource`. And there is no `dataSource` in Mtx-grid. Is it possible or could be upgraded to have this feature ?

**Comment by nzbin** [comment]
> When using material table we can init data with `dataSource`. And there is no `dataSource` in Mtx-grid. Is it possible or could be upgraded to have this feature ?

@ramax495 I'm sorry, I don't quite understand what you mean. You can use the `dataSource` with the grid instance.
https://github.com/ng-matero/extensions/blob/16d54b6435fb738060ee273a4dd37c9e5a304f18/projects/extensions/grid/grid.ts#L194

**Comment by ramax495** [comment]
@nzbin I mean Input property that mat-table has:
https://github.com/angular/components/blob/main/src/cdk/table/table.ts#L498

`@Input()  get dataSource(): CdkTableDataSourceInput<T>`

where `CdkTableDataSourceInput` is:

```
/** Possible types that can be set as the data source for a `CdkTable`. */
export type CdkTableDataSourceInput<T> = readonly T[] | DataSource<T> | Observable<readonly T[]>;
```

In my case I have `dataSource` type that is derived from DataSource (from @angular/cdk/collections). 
When I use mat-table I can pass to input parameters my dataSource like this: `[dataSource]="dataSource"`.
In mtx-grig only array is allowed:
https://github.com/ng-matero/extensions/blob/main/projects/extensions/grid/grid.ts#L201

**Comment by nzbin** [comment]
> @nzbin I mean Input property that mat-table has: https://github.com/angular/components/blob/main/src/cdk/table/table.ts#L498
> 
> `@Input() get dataSource(): CdkTableDataSourceInput<T>`
> 
> where `CdkTableDataSourceInput` is:
> 
> ```
> /** Possible types that can be set as the data source for a `CdkTable`. */
> export type CdkTableDataSourceInput<T> = readonly T[] | DataSource<T> | Observable<readonly T[]>;
> ```
> 
> In my case I have `dataSource` type that is derived from DataSource (from @angular/cdk/collections). When I use mat-table I can pass to input parameters my dataSource like this: `[dataSource]="dataSource"`. In mtx-grig only array is allowed: https://github.com/ng-matero/extensions/blob/main/projects/extensions/grid/grid.ts#L201

I'm sorry, `mtx-grid` is not exactly equal with `mat-table`. If you have any other ideas, please give me a PR.
