### ISSUE TITLE
V12 Roadmap

### ISSUE THREAD

**Issue by nzbin** [ng-matero/extensions#65]
- [x] add new component `datetimepicker`
- [x] add new component `range-slider`
- [x] add new options to support 12 positions of popover
- [x] redesign `colorpicker`
- [x] add global config
